const samplePGs = [
  {
    name: 'Sunshine Boys Hostel',
    description: 'Premium boys PG accommodation near NITK Surathkal with modern amenities and homely food.',
    rent: 8000,
    deposit: 10000,
    gender: 'boys',
    foodIncluded: true,
    acAvailable: true,
    sharingType: 'double',
    area: 'Surathkal',
    collegeNearby: ['NITK Surathkal', 'Canara Engineering College'],
    address: '123, Near NITK Gate, Surathkal, Mangalore',
    latitude: 12.9634,
    longitude: 74.8064,
    images: ['https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800'],
    amenities: ['WiFi', 'Laundry', 'CCTV', 'Hot Water', 'RO Water', 'Housekeeping', 'Furnished', 'Attached Bathroom'],
    contactNumber: '+91 9876543210',
    contactName: 'Rajesh Kumar',
    featured: true
  },
  {
    name: 'Green Valley Ladies Hostel',
    description: 'Safe and comfortable ladies PG near St Aloysius College.',
    rent: 7500,
    deposit: 8000,
    gender: 'girls',
    foodIncluded: true,
    acAvailable: false,
    sharingType: 'triple',
    area: 'Hampankatta',
    collegeNearby: ['St Aloysius College', 'Mangalore University'],
    address: '45, Near St Aloysius College, Hampankatta, Mangalore',
    latitude: 12.8785,
    longitude: 74.8423,
    images: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800'],
    amenities: ['WiFi', 'CCTV', 'Hot Water', 'Security Guard', 'Housekeeping', 'Geysers'],
    contactNumber: '+91 9876543211',
    contactName: 'Priya Sharma',
    featured: true
  },
  {
    name: 'City Center PG',
    description: 'Affordable PG accommodation in the heart of Mangalore city.',
    rent: 6000,
    deposit: 7000,
    gender: 'co-ed',
    foodIncluded: false,
    acAvailable: false,
    sharingType: 'triple',
    area: 'Mangalore City',
    collegeNearby: ['Yenepoya University', 'Srinivas University'],
    address: '78, City Center Road, Mangalore',
    latitude: 12.9141,
    longitude: 74.8560,
    images: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800'],
    amenities: ['WiFi', 'Parking', 'Power Backup', 'RO Water', 'Common Kitchen'],
    contactNumber: '+91 9876543212',
    contactName: 'Mohammed Ali'
  },
  {
    name: 'AK Residency',
    description: 'Modern PG near AJ Institute with AC rooms and premium facilities.',
    rent: 10000,
    deposit: 15000,
    gender: 'boys',
    foodIncluded: true,
    acAvailable: true,
    sharingType: 'single',
    area: 'Kankanady',
    collegeNearby: ['AJ Institute', 'KMC Mangalore'],
    address: '23, AJ Institute Road, Kankanady, Mangalore',
    latitude: 12.8955,
    longitude: 74.8468,
    images: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800'],
    amenities: ['WiFi', 'Laundry', 'CCTV', 'Hot Water', 'RO Water', 'Housekeeping', 'Furnished', 'Attached Bathroom', 'Geysers', 'Gym'],
    contactNumber: '+91 9876543213',
    contactName: 'Arjun Reddy',
    featured: true
  },
  {
    name: 'Lakshmi Ladies PG',
    description: 'Home-like stay for girls near Srinivas University.',
    rent: 6500,
    deposit: 8000,
    gender: 'girls',
    foodIncluded: true,
    acAvailable: false,
    sharingType: 'double',
    area: 'Bejai',
    collegeNearby: ['Srinivas University', 'SDM College'],
    address: '56, Bejai Layout, Mangalore',
    latitude: 12.8820,
    longitude: 74.8430,
    images: ['https://images.unsplash.com/photo-1536376072261-38c75010e6c9?w=800'],
    amenities: ['WiFi', 'CCTV', 'Hot Water', 'Security Guard', 'Common Kitchen', 'Garden'],
    contactNumber: '+91 9876543214',
    contactName: 'Lakshmi Devi'
  },
  {
    name: 'Nearby Boys Hostel',
    description: 'Budget-friendly boys PG with all basic amenities.',
    rent: 5500,
    deposit: 6000,
    gender: 'boys',
    foodIncluded: false,
    acAvailable: false,
    sharingType: 'triple',
    area: 'Surathkal',
    collegeNearby: ['NITK Surathkal', 'Canara Engineering College'],
    address: '90, Surathkal Main Road, Mangalore',
    latitude: 12.9590,
    longitude: 74.8100,
    images: ['https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800'],
    amenities: ['WiFi', 'Parking', 'Power Backup', 'RO Water', 'Common Kitchen', 'TV Room'],
    contactNumber: '+91 9876543215',
    contactName: 'Suresh Pai'
  },
  {
    name: 'Cozy Corners PG',
    description: 'Well-maintained PG with modern interiors.',
    rent: 7000,
    deposit: 9000,
    gender: 'co-ed',
    foodIncluded: true,
    acAvailable: true,
    sharingType: 'double',
    area: 'Kadri',
    collegeNearby: ['Yenepoya University', 'Mangalore University'],
    address: '34, Kadri Hills, Mangalore',
    latitude: 12.8760,
    longitude: 74.8530,
    images: ['https://images.unsplash.com/photo-1540518614846-7eded433c457?w=800'],
    amenities: ['WiFi', 'Laundry', 'CCTV', 'Hot Water', 'Housekeeping', 'Furnished', 'Microwave', 'Refrigerator'],
    contactNumber: '+91 9876543216',
    contactName: 'Deepak Shetty',
    featured: true
  },
  {
    name: 'Mangalore Homes',
    description: 'Premium co-ed PG with homely atmosphere.',
    rent: 8500,
    deposit: 12000,
    gender: 'co-ed',
    foodIncluded: true,
    acAvailable: true,
    sharingType: 'single',
    area: 'Falnir',
    collegeNearby: ['St Aloysius College', 'Srinivas University'],
    address: '12, Falnir Road, Mangalore',
    latitude: 12.8710,
    longitude: 74.8400,
    images: ['https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?w=800'],
    amenities: ['WiFi', 'Laundry', 'CCTV', 'Hot Water', 'RO Water', 'Housekeeping', 'Furnished', 'Attached Bathroom', 'Washing Machine'],
    contactNumber: '+91 9876543217',
    contactName: "Anita D'Souza",
    featured: true
  },
  {
    name: 'Students Inn',
    description: 'Affordable hostel for engineering students.',
    rent: 5000,
    deposit: 5000,
    gender: 'boys',
    foodIncluded: false,
    acAvailable: false,
    sharingType: 'multiple',
    area: 'Kapikad',
    collegeNearby: ['Canara Engineering College', 'SDM College'],
    address: '67, Kapikad Road, Mangalore',
    latitude: 12.9200,
    longitude: 74.8650,
    images: ['https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800'],
    amenities: ['WiFi', 'Parking', 'Power Backup', 'Study Room', 'TV Room'],
    contactNumber: '+91 9876543218',
    contactName: 'Vinod Krishna'
  },
  {
    name: 'Rose Garden Ladies PG',
    description: 'Beautiful garden PG for girls.',
    rent: 7000,
    deposit: 8000,
    gender: 'girls',
    foodIncluded: true,
    acAvailable: true,
    sharingType: 'double',
    area: 'Boloor',
    collegeNearby: ['St Aloysius College', 'Yenepoya University'],
    address: '23, Boloor Cross, Mangalore',
    latitude: 12.8680,
    longitude: 74.8380,
    images: ['https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=800'],
    amenities: ['WiFi', 'CCTV', 'Hot Water', 'Security Guard', 'Garden', 'Geysers', 'Attached Bathroom'],
    contactNumber: '+91 9876543219',
    contactName: 'Mary Thomas',
    featured: true
  }
];

module.exports = samplePGs;
